# This file was automatically generated by rails. Its purpose is to gracefully
# move from using ActiveRecod::Base (used by rails until version 4.2) to using
# ApplicationRecord (used by rails starting at version 5). By using
# ApplicationRecord, changes you make to this class are local to this app
# instead of infecting everything that uses ActiveRecord::Base. For more info:
# https://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html

class ApplicationRecord < ActiveRecord::Base
  # this line was automatically generated - it seems to somehow make this class abstract
  self.abstract_class = true
end
